project:
  type: website

website:
  title: "ClassroomPlus Extensiones para Classroom API en Google Apps Script"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true